spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 50MB #I don't want files bigger than 50MB, its no need to take it down to 10MB for each file - since i want the present each project fully.
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls: true
      debug: true
      enable: true
      required: true #I don't really need all these properties since they are set in the emailConfig, but i'll just leave it here for further development or changes later.

jwt:
  secret: ${JWT_SECRET}